import { test, expect } from '@playwright/test'
import { clearAppStorage, setupWorkspace, createAndStartSprint, generateStoriesWithAI } from './helpers'

test.beforeEach(async ({ page }) => {
  await page.goto('/')
  await clearAppStorage(page)
  await page.reload()
  await setupWorkspace(page)
  await createAndStartSprint(page)
  await generateStoriesWithAI(page)
})

test.describe('Kanban Board', () => {
  test('board loads with stories in To Do column', async ({ page }) => {
    await page.goto('/board')
    await expect(page.getByText('Active Sprint Board')).toBeVisible()
    await expect(page.getByText('To Do')).toBeVisible()
    // Stories generated by AI mock should be in To Do
    const cards = page.locator('.kanban-column').first().locator('.bg-\\[\\#1a1f2e\\]')
    await expect(cards.first()).toBeVisible()
  })

  test('clicking a story card opens the detail sheet', async ({ page }) => {
    await page.goto('/board')
    const card = page.locator('.bg-\\[\\#1a1f2e\\]').first()
    await card.click()
    // Sheet should open
    await expect(page.locator('[role="dialog"]')).toBeVisible({ timeout: 5000 })
  })

  test('story detail shows acceptance criteria', async ({ page }) => {
    await page.goto('/board')
    await page.locator('.bg-\\[\\#1a1f2e\\]').first().click()
    await expect(page.getByRole('heading', { name: /Acceptance Criteria/ })).toBeVisible()
  })

  test('End Sprint button visible for admin', async ({ page }) => {
    await page.goto('/board')
    await expect(page.getByRole('link', { name: /end sprint/i })).toBeVisible()
  })

  test('sprint header shows progress bars', async ({ page }) => {
    await page.goto('/board')
    // Progress bars in sprint header
    await expect(page.getByText(/% done/)).toBeVisible()
    await expect(page.getByText(/% time/)).toBeVisible()
  })
})
